[package]
name = "egui-table-click"
version = "0.1.0"
authors = ["Valeriy V. Vorotyntsev <valery.vv@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { git = "https://github.com/vvv/egui.git", branch = "table-row-col-sense", package = "eframe" }
egui_demo_lib = { git = "https://github.com/vvv/egui.git", branch = "table-row-col-sense", package = "egui_demo_lib" }
egui_extras = { git = "https://github.com/vvv/egui.git", branch = "table-row-col-sense", package = "egui_extras" }
tracing-subscriber = "0.3"
